/**
 * Single source of truth for everything SEO-related.
 * Change values here — layout metadata, sitemap, robots and JSON-LD all read from this.
 */
export const site = {
  /** Production origin. Set NEXT_PUBLIC_SITE_URL on the host; the fallback is only for local dev. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000").replace(/\/$/, ""),
  name: "Buy.am",
  shortName: "Buy.am",
  title: "Buy.am — օնլայն շուկա",
  titleTemplate: "%s | Buy.am",
  description:
    "Buy.am — ապրանքների և ծառայությունների օնլայն շուկա Հայաստանում։ Հազարավոր ապրանքներ, արագ առաքում և ապահով վճարում։",
  /** BCP-47 tag used for <html lang> and og:locale. */
  locale: "hy-AM",
  ogLocale: "hy_AM",
  /** Generated by src/app/opengraph-image.tsx (1200x630). */
  ogImage: "/opengraph-image",
  twitter: "@buyam",
  keywords: [
    "buy.am",
    "օնլայն շուկա",
    "առցանց խանութ",
    "ապրանքներ Հայաստանում",
  ],
} as const;

export const absoluteUrl = (path = "/") => `${site.url}${path.startsWith("/") ? path : `/${path}`}`;
