import { company } from "./content";

/**
 * Single source of truth for everything SEO-related.
 * Change values here — layout metadata, sitemap, robots and JSON-LD all read from this.
 */
export const site = {
  /** Production origin. Set NEXT_PUBLIC_SITE_URL on the host; the fallback is only for local dev. */
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000").replace(/\/$/, ""),
  name: company.legalName,
  shortName: company.name,
  title: "ԱՐԿՈՄՊ ՍՊԸ — ռետինե, ասբոտեխնիկական և մետաղյա արտադրանքի մատակարար Երևանում",
  titleTemplate: "%s | ԱՐԿՈՄՊ ՍՊԸ",
  description:
    "ԱՐԿՈՄՊ ՍՊԸ-ն Երևանում մատակարարում է ռետինե և ասբոտեխնիկական արտադրանք, պողպատյա ճոպանալարեր, բեռնափոխադրիչ ժապավեններ, բարձր ճնշման խողովակներ և պաշտպանիչ միջոցներ՝ 22 ապրանքախումբ մեկ հասցեով։",
  /** BCP-47 tag used for <html lang> and og:locale. */
  locale: "hy-AM",
  ogLocale: "hy_AM",
  /** Generated by src/app/opengraph-image.tsx (1200x630). */
  ogImage: "/opengraph-image",
  keywords: [
    "ԱՐԿՈՄՊ",
    "arkomp",
    "պողպատյա ճոպանալարեր",
    "ռետինե խողովակներ",
    "բեռնափոխադրիչ ժապավեններ",
    "պարոնիտ",
    "ասբոտեխնիկական նյութեր",
    "դիէլեկտրիկ ապրանքներ",
    "արտադրական նյութեր Երևան",
  ],
} as const;

export const absoluteUrl = (path = "/") => `${site.url}${path.startsWith("/") ? path : `/${path}`}`;
